SELECT CASE WHEN EXISTS (SELECT WEB_URL FROM SQL.WEBSITE WHERE SQL.WEBSITE.WEB_URL=${url}) THEN 1 ELSE 0 end as CD from SQL.ACCESS_METHOD;


SELECT CASE WHEN EXISTS (SELECT WEB_URL FROM SQL.WEBSITE WHERE SQL.WEBSITE.WEB_URL='www.maver.com') THEN 1 ELSE 0 end as CD from SQL.ACCESS_METHOD