CREATE USER SQL IDENTIFIED BY 1234;
ALTER USER SQL ACCOUNT UNLOCK;
GRANT RESOURCE, DBA, CONNECT TO SQL;

CREATE TABLESPACE SQL_DATA
datafile '/u01/app/oradata/SQL_DATA.dbf' SIZE 10G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE SQL_TEMP
TEMPFILE '/u01/app/oradata/SQL_TEMP.dbf' SIZE 1G
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
;


ALTER USER SQL DEFAULT TABLESPACE SQL_DATA;
ALTER USER SQL TEMPORARY TABLESPACE SQL_TEMP;

