CREATE SEQUENCE SQL.ACCESS_SEQUENCE
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 999999;

CREATE SEQUENCE SQL.OS_SEQUENCE
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 99999;

CREATE SEQUENCE SQL.MODEL_SEQUENCE
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 99999;

CREATE SEQUENCE SQL.MANU_SEQUENCE
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 99999;

CREATE SEQUENCE SQL.WEB_SEQUENCE
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 999;

COMMIT;